#!/bin/bash
apt-get update && apt-get upgrade 
apt-get install curl 
apt-get install apache2 
apt-get install php5 libapache2-mod-php5 php5-mcrypt 
service apache2 restart
apt-get install mysql-server php5-mysql 
mysql_install_db
mysql_secure_installation
apt-get install phpmyadmin 
php5enmod mcrypt
service apache2 restart
ln -s /usr/share/phpmyadmin /var/www/html/phpmyadmin
apt-get install libssh2-1-dev libssh2-php 
php -m |grep ssh2
service apache2 restart
cd /var/www/html
wget https://github.com/fabiokim/Painel/painel4.zip
apt-get install unzip 
unzip painel4.zip
rm painelssh.zip index.html
clear
